# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy to Vercel

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "vercel-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      ADMIN_INVITE_CODE: ${{ secrets.ADMIN_INVITE_CODE }}
      TEACHER_INVITE_CODE: ${{ secrets.TEACHER_INVITE_CODE }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      ENV_CHECK_TOKEN: ${{ secrets.ENV_CHECK_TOKEN }}
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env.local file
        run: |
          echo "MONGODB_URI=$MONGODB_URI" > .env.local
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env.local
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.local
          echo "ADMIN_INVITE_CODE=$ADMIN_INVITE_CODE" >> .env.local
          echo "TEACHER_INVITE_CODE=$TEACHER_INVITE_CODE" >> .env.local
          echo "CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME" >> .env.local
          echo "CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY" >> .env.local
          echo "CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET" >> .env.local
          echo "ENV_CHECK_TOKEN=$ENV_CHECK_TOKEN" >> .env.local
      
      - name: Verify .env.local
        run: |
          ls -la .env.local
          echo "First few lines of .env.local (without showing values):"
          grep -v "^$" .env.local | cut -d= -f1 | sort
          cat .env.local | sed 's/=.*/=***/'
      
      - name: Check environment variables
        run: |
          echo "Checking environment variables..."
          echo "MONGODB_URI defined: $(if [ -n \"$MONGODB_URI\" ]; then echo 'yes'; else echo 'no'; fi)"
          echo "NEXTAUTH_SECRET defined: $(if [ -n \"$NEXTAUTH_SECRET\" ]; then echo 'yes'; else echo 'no'; fi)"
          echo "NEXTAUTH_URL defined: $(if [ -n \"$NEXTAUTH_URL\" ]; then echo 'yes'; else echo 'no'; fi)"
          
      - name: Build with environment variables
        run: |
          echo "Building with Next.js..."
          export MONGODB_URI="$MONGODB_URI"
          export NEXTAUTH_URL="$NEXTAUTH_URL"
          export NEXTAUTH_SECRET="$NEXTAUTH_SECRET"
          export ADMIN_INVITE_CODE="$ADMIN_INVITE_CODE"
          export TEACHER_INVITE_CODE="$TEACHER_INVITE_CODE"
          export CLOUDINARY_CLOUD_NAME="$CLOUDINARY_CLOUD_NAME"
          export CLOUDINARY_API_KEY="$CLOUDINARY_API_KEY"
          export CLOUDINARY_API_SECRET="$CLOUDINARY_API_SECRET"
          export ENV_CHECK_TOKEN="$ENV_CHECK_TOKEN"
          export NEXT_PHASE="phase-production-build"
          npm run build
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          ADMIN_INVITE_CODE: ${{ secrets.ADMIN_INVITE_CODE }}
          TEACHER_INVITE_CODE: ${{ secrets.TEACHER_INVITE_CODE }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          ENV_CHECK_TOKEN: ${{ secrets.ENV_CHECK_TOKEN }}
